[workspace]
members = [
  "oprish",
  "pandemonium",
  "effis",
  "todel",
  "cli",
  "codegen",
  "integration-tests",
]

[workspace.package]
version = "0.4.0-alpha1"
documentation = "https://eludevs.pages.dev"
