version: "3"

x-restart-policy:
  &restart-policy
  restart: unless-stopped

services:
  oprish:
    <<: *restart-policy
    depends_on: ["keydb", "postgresql"]

    environment:
      - DATABASE_URL=postgresql://root:root@postgresql/eludris
      - REDIS_URL=redis://keydb:6379
    volumes:
      - type: bind
        source: Eludris.toml
        target: /Eludris.toml
      - type: bind
        source: static
        target: /static
    build:
      context: .
      dockerfile: oprish/Dockerfile
    pull_policy: build

  pandemonium:
    extends:
      service: oprish
    depends_on: ["oprish"]
    build:
      dockerfile: pandemonium/Dockerfile

  effis:
    extends:
      service: oprish
    depends_on: ["oprish"]
    volumes:
      - type: bind
        source: ./files
        target: /files
    build:
      dockerfile: effis/Dockerfile

  keydb:
    <<: *restart-policy
    image: eqalpha/keydb
    volumes:
      - "./keydb:/data"

  postgresql:
    <<: *restart-policy
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: eludris
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
