name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Formatting

    # Do not run on PRs from the same repo, since `push` already handles them.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Tests

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - run: docker-compose -f tests/docker-compose.yml up -d

      - name: Install sqlx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli

      - name: Run migrations
        run: sqlx migrate run --database-url postgresql://root:root@127.0.0.1:5432/eludris

      - name: Test Eludris
        run: ./test.py --logs
        env:
          REDIS_URL: "redis://127.0.0.1:6379"
          DATABASE_URL: "postgresql://root:root@127.0.0.1:5432/eludris"

  clippy:
    name: Clippy; Destroyer of Realities.

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - run: docker-compose -f tests/docker-compose.yml up -d

      - name: Install sqlx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli

      - name: Run migrations
        run: sqlx migrate run --database-url postgresql://root:root@127.0.0.1:5432/eludris

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
